# Generated by Django 5.0.14 on 2025-05-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0004_user_avatar_alter_user_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('moderator', 'moderator'), ('user', 'user')],
                                   default='user', max_length=9),
        ),
    ]
